config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :articles
  root 'welcome#index'
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
        def index
                @articles = Article.all
              end
        def show
                @article = Article.find(params[:id])
              end
        def new        
        end
        def create
                @article = Article.new(article_params)
              
                @article.save
                redirect_to @article
              end
              
              private
                def article_params
                  params.require(:article).permit(:title, :text)
                end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<div class="container">
<div class="row">
<div class="col align-self-center">
<h1 class="text-center">New article</h1>
<%= form_with scope: :article, url: articles_path, local: true, html: {class: 'col-4'} do |form| %>
  <p>

    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit :class => 'btn btn-success' %>
  </p>
<% end %>
</div>
</div>
</div>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

app/views/blocks/_footer.html.erb
<footer>
        <div class="conteiner-footer">
          <div class="row">
            <div class="col">
              <img class="sss" src="<%= image_path('sssss.png') %>">
              <button type="button" class="btn btn-outline-light">English</button>
              <p class="post-footer">All rights reserved. © Space. 2019 Htmlstream.</p>
            </div>
            <div class="col">
              <p class="act-footer">About</p>
              <p class="footer-item">About Agency</p>
              <p class="footer-item">About Start-Up</p>
              <p class="footer-item">Services Agency</p>
              <p class="footer-item">Services Start-Up</p>
            </div>
            <div class="col">
              <p class="act-footer">Company</p>
              <p class="footer-item">Contact Us</p>
              <p class="footer-item">Help</p>
              <p class="footer-item">Careers</p>
              <p class="footer-item">Terms & Conditions</p>
              <p class="footer-item">Privacy & Policy</p>
            </div>
            <div class="col">
              <p class="act-footer">Shop</p>
              <p class="footer-item">Classic</p>
              <p class="footer-item">Single Product</p>
              <p class="footer-item">Checkout</p>
            </div>
            <div class="col">
              <p class="act-footer">Social</p>
              <p class="footer-item">Facebook</p>
              <p class="footer-item">Twitter</p>
              <p class="footer-item">Dribbble</p>
              <p class="footer-item">GitHub</p>
            </div>
          </div>
        </div>
      </footer>

app/views/blocks/_head.html.erb
<head>
    <title>Blog5</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="animate.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&display=swap" rel="stylesheet">
    <script>
      new WOW().init();
    </script>
    <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.11"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="js/typed.js" type="text/javascript"></script>
    <title>IABS TEST BOOTSTRAP  2</title>
  </head>

app/views/blocks/_header.html.erb
 <header style="background-image: url('<%= image_path('Rectangle.png') %>'); background-size: cover;">
          <div class="image">
            <nav class="navbar">
              <a class="navbar-brand" href="#">
                <img  class="logo" src="<%= image_path('Frame.png') %>" width="133" height="36" left="15"
          top="18" alt="">
              </a>
              <ul class="nav justify-content-end">
                <li class="nav-item">
                  <a class="nav-link active" href="#">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">Pages</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">Works</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">Blog</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">Shop</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">Docs</a>
                </li>
              </ul>
              <button type="button" class="btn btn-success">Sign in</button>
              <div class="icons">
                <i class="fab fa-youtube"></i>
                <i class="fab fa-facebook-f"></i>
                <i class="fab fa-instagram"></i>
              </div>
            </nav>
            <h6>Join the change</h6>
            <section class="wow slideInLeft" data-wow-duration="2s" data-wow-delay="5s"> 
              <h2>Space service that moves work forward</h2>
            </section>
            <form id="register-form">
              <div class="form-group">
                <label for="formGroupExampleInput">Get started for free</label>
                <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Enter your username">
              </div>
              <div class="form-group">
                <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Enter your email address">
              </div>
              <div class="form-group">
                <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Enter your password">
              </div>
              <button class=" btn header-btn">Get Started</button>
            </form>
          </div>
        </header>

app/views/blocks/_scripts.html.erb
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="js/wow.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="js/typed.js" type="text/javascript"></script>
    <script>
      $(document).ready(function(){
            var typed = new Typed('#typed', {
          stringsElement: '#typed-strings',
          typeSpeed: 40,
          });
      });
    </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<%= render('blocks/head') %>
  <body>
      <%= render('blocks/header') %>
        <%= yield %>
      <%= render('blocks/footer') %>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <%= render('blocks/scripts') %>
  </body>
</html>

app/views/welcome/index.html.erb
<main>
  <div id="partners">
    <div class="row">
      <div class="col"><img src="<%= image_path('spotify.png') %>" alt="#"></div>
      <div class="col"><img src="<%= image_path('amason.png') %>" alt="#"></div>
      <div class="col"><img src="<%= image_path('google.png') %>" alt="#"></div>
      <div class="col"><img src="<%= image_path('paypal.png') %>" alt="#"></div>
      <div class="col"><img src="<%= image_path('slack.png') %>" alt="#"></div>
      <div class="col"><img src="<%= image_path('samsung.png') %>" alt="#"></div>
      <div class="col"><img src="<%= image_path('airbnd.png') %>" alt="#"></div>
      <div class="col"><img src="<%= image_path('lenovo.png') %>" alt="#"></div>
    </div>
    <div class="line"> <hr></div>
  </div>
  <div class='container'>
    <div class='row'>
    <div class='col-12'>
    <h2>My articles</h2>
    <%= link_to 'My Blog', controller: 'articles' %>
    </div>
    </div>
  </div>
  <div class="conteiner-1">
    <div class="wrapper">
      <div class="two">
        <img class="pic-green" src="<%= image_path('green.png') %>">
        <p class="untitle">This is where we sit down, grab a cup of coffee and dial in the details. Understanding the task at hand and ironing out the wrinkles is key.</p>
        <p><a href="#">Learn More</a></p>
      </div>
      <div class="three">
        <p class="title">3 methods Space can help to grow your business with</p>
        <ol>
          <li class="group-1"><a href="#">Features</a></li>
          <li class="group-1"><a href="#">Key Benefits</a></li>
          <li class="group-1"><a href="#">Components</a></li>
        </ol>
      </div>
      <div class="four">
        <img class="pic-yellow" src="<%= image_path('yellow.png') %>">
        <p class="untitle">Now that we've aligned the details, it's time to get things mapped out and organized. This part is really crucial in keeping the project in line to completion.</p>
        <p><a href="#">Learn More</a></p>
      </div>
      <div class="five">
        <img class="pic-blue" src="<%= image_path('blue.png') %>">
        <p class="untitle">The time has come to bring those ideas and plans to life. This is where we really begin to visualize your napkin sketches and make them into beautiful pixels.</p>
        <p><a href="#">Learn More</a></p>
      </div>
      <div class="six"> <img class="pic-purple" src="<%= image_path('purple.png') %>">
        <p class="untitle">Whether through commerce or just an experience to tell your brand's story, the time has come to start using development languages that fit your projects needs.</p>
        <p><a href="#">Learn More</a></p>
      </div>
    </div>
  </div>
  <div class="conteiner-2">
    <div class="slide-header">
      <button type="button" class="block_btn" class="btn btn-light">Key features</button>
      <p class="block-title">Create high quality products</p>
      <p class="block-subtitle">See how creating and moving projects forward in Space will help your to stay in sync, hit deadlines, and reach your goals.</p>
    </div>
    <div class="carusel">
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="<%= image_path('slide/slide1.jpg') %>" class="d-block w-100" alt="Slide 1">
          </div>
          <div class="carousel-item">
            <img src="<%= image_path('slide/slide2.jpg') %>" class="d-block w-100" alt="Slide 2">
          </div>
          <div class="carousel-item">
            <img src="<%= image_path('slide/slide3.jpg') %>" class="d-block w-100" alt="Slide 3">
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
  </div>
  <div class="conteiner-3">
    <div class="card-header">
      <button type="button" class="block_btn" class="btn btn-light">Pricing plans</button>
      <p class="block-title">No additional costs. Pay for what you use.</p>
      <p class="block-subtitle">Choose the most suitable service for your needs with reasonable price.</p>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-sm">
          <div class="card">
            <div class="container">
              <div class="card-1">
                <p>Start</p>
                <h4><b>Free</b></h4>
                <p>Community support</p>
                <p>400+ pages</p>
                <p>100+ header variations</p>
                <p>20+ home page options</p>
                <button class="cards">Start Free Trial</button>
              </div>
            </div>
          </div>
        </div>
        <div class="col-sm">
          <div class="activ-card">
            <div class="container">
              <div class="card-2">
                <p>Growing</p>
                <h4><b>$39</b>/month</h4>
                <p>Community support</p>
                <p>400+ pages</p>
                <p>100+ header variations</p>
                <p>20+ home page options</p>
                <button class="activ-cards">Subscibe Now</button>
              </div>
            </div>
          </div>
        </div>
        <div class="col-sm">
          <div class="card">
            <div class="container">
              <div class="card-3">
                <p>Enterprise</p>
                <h4><b>Team</b></h4>
                <p>Community support</p>
                <p>400+ pages</p>
                <p>100+ header variations</p>
                <p>20+ home page options</p>
                <button class="cards">Start Free Trial</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="conteiner-4">
    <div class="row">
      <div class="col-sm-6">
        <img class="woman" src="<%= image_path('comment1.png') %>">
        <p class="comment-name">Maria Muzynska</p>
        <p class="comment">"I love Space! I love the ease of use, I love the fact that I have total creative freedom. The template is really nice and offers quite a large set of options. It's beautiful and the coding is done quickly and seamlessly."</p>
      </div>
      <div class="col-sm-6">
        <img class="man" src="<%= image_path('comment2.png') %>">
        <p class="comment-name-1">Markus Brown</p>
        <p class="comment-1">"We are incredibly impressed with Space and how well it supports its customers with amazing products and services. One simple subscription gives you access to all our tools, plus so much more."</p>
      </div>
    </div>
    <div class="row">
      <div class="col-sm">
        <img id="image-footer" class="image-footer" src="<%= image_path('footerimg.png') %>" alt="#" width="1346" height="252">
        <p class="title-pre-footer">Get started with Space</p>
        <p class="subtitle-pre-footer">Space gives you everything you need to manage business, build great stuff, and reach your goals.</p>
        <button type="button" class="btn btn-primary">Create Free Account</button>
        <button type="button" class="btn btn-secondary">Learn More</button>
      </div>
    </div>
  </div>
</div>
</main>